apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 1c-users-data
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: 1c-users-data
